sudo: false
language: python
cache: pip
python:

  - "2.7"
install:
  - pip install --trusted-host pypi.python.org -r requirements.txt
script:
  - pytest test_unit.py -sv
  #- if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pre-commit run --all-files; 
#after_success:
 # - codecov