sudo: true
language: python
cache: pip
python:

  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y swig
  - sudo apt-get install -y libpulse-dev
install:
  - pip install --trusted-host pypi.python.org -r requirements.txt
script:
  - pytest test_unit.py -sv
  #- if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pre-commit run --all-files; 
#after_success:
 # - codecov