version: "3.3"
services:
  unfetter-insight:
    build: .
    container_name: unfetter-insight
    image: unfetter-insight
    ports:
     - "5000:5000"
    volumes:
     - ./:/app
    entrypoint:
      - gunicorn
      - --config
      - gunicorn_config.py
      - app:app

    